# Generic CONGA task which gathers the CONGA facts for the current node/role/variant
# ensures that all conga directories exist and copies over all files that CONGA
# has generated for that combination.

- name: Setup files, directories lists and result fact.
  set_fact:
    _conga_directories: "{{ conga_files_directories }}"
    _conga_files: "{{ conga_files_files }}"
    conga_files_changed: false

- name: Map list of files to their paths.
  set_fact:
    _conga_files: "{{ _conga_files | map(attribute='path') | list }}"
  when: (_conga_files | first) is mapping

- name: Filter files and directories lists.
  set_fact:
    _conga_directories: "{{ _conga_directories | select('match', conga_files_filter) | list }}"
    _files: "{{ _conga_files | select('match', conga_files_filter) | list }}"
  when: conga_files_filter is defined

- name: Ensure CONGA directories.
  file:
    path: "{{ conga_files_base_path }}/{{ item | regex_replace(conga_files_strip, '') }}"
    state: directory
    owner: "{{ conga_files_owner | default(omit) }}"
    group: "{{ conga_files_group | default(omit) }}"
  with_items: "{{ _conga_directories }}"

- name: Copy CONGA files.
  copy:
    src: "{{ conga_config_path }}/{{ item }}"
    dest: "{{ conga_files_base_path }}/{{ item | regex_replace(conga_files_strip, '') }}"
    owner: "{{ conga_files_owner | default(omit) }}"
    group: "{{ conga_files_group | default(omit) }}"
    mode: "{{ conga_files_mode | default(omit) }}"
  with_items: "{{ _conga_files }}"
  register: _conga_files_result
  notify: "{{ conga_files_handlers | default(omit) }}"

- name: "Set 'conga_files_changed' to true when changed." # noqa 503
  set_fact:
    conga_files_changed: true
  when: _conga_files_result.changed